name: Sync Crowdin locales

on:
  workflow_dispatch:
  push:
    branches: [cosine]

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: crowdin action
        uses: crowdin/github-action@8f01d54f70f1713ee3f09d82c2bbb2daeac28689 # v2.17.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_cosine
          create_pull_request: true
          pull_request_title: "New Crowdin updates"
          pull_request_body: "New Crowdin translations and locales. (automated)"
          pull_request_base_branch_name: "cosine"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
