name: Upload signed executables

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "GitHub Actions run_id when created the corresponding release"
        required: true
        type: string

permissions:
  id-token: write
  attestations: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download build info
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ inputs.run_id }}
        run: gh run download "${RUN_ID}" --name "info" --dir info

      - name: Download signed files
        shell: bash
        timeout-minutes: 10
        env:
          SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
          ORGANIZATION_ID: 1324b51a-cb3d-4d1e-aab7-27b1169bd402
        run: |
          SIGNING_REQUEST_ID=$(cat info/signing-request-id.txt)
          REQUEST_URL=https://app.signpath.io/API/v1/${ORGANIZATION_ID}/SigningRequests/${SIGNING_REQUEST_ID}

          # Check SignPath status
          status=InProgress
          while [ "$status" = "InProgress" ]; do
            status=$(curl -f --silent -H "Authorization: Bearer ${SIGNPATH_API_TOKEN}" ${REQUEST_URL} \
              | jq -r .status)

            echo "SignPath status: $status"
            case "$status" in
              WaitingForApproval)
                echo "Not approved yet. Approve it first:"
                cat info/signing-request-web-url.txt
                exit 1
                ;;
              InProgress)
                ;;
              Completed)
                break
                ;;
              *)
                exit 1
                ;;
            esac

            sleep 10
          done

          # Download the signed files
          curl -f -H "Authorization: Bearer ${SIGNPATH_API_TOKEN}" \
               -o package.zip \
               ${REQUEST_URL}/SignedArtifact
          unzip package.zip -d package

          rm -f package/*_pdb.*

          for i in package/sine-win-*-unsigned.exe; do
            [ -f "$i" ] || continue
            mv "$i" "${i/-unsigned/}"
          done

          ls -l package

      - name: Upload signed executables
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: signed-package
          path: |
            ./package/*

      - name: Attest
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: ./package/*
